In [9]:
import pandas as pd
import datetime
import pandas_datareader.data as web
import numpy as np

# 时间 time&date

In [16]:
start = datetime.datetime(2010, 1, 1)
end = datetime.datetime.now()

In [41]:
now = pd.Timestamp.now()#获取当前时间，但是不分时区

In [42]:
now_shanghai = now.tz_localize('Canada/Atlantic')#这个不知道为什么没有用
now_shanghai

Timestamp('2019-08-13 16:24:24.880777-0300', tz='Canada/Atlantic')

In [32]:
import pytz
pytz.common_timezones#获得几个时区的表示方法

['Africa/Abidjan', 'Africa/Accra', 'Africa/Addis_Ababa', 'Africa/Algiers', 'Africa/Asmara', 'Africa/Bamako', 'Africa/Bangui', 'Africa/Banjul', 'Africa/Bissau', 'Africa/Blantyre', 'Africa/Brazzaville', 'Africa/Bujumbura', 'Africa/Cairo', 'Africa/Casablanca', 'Africa/Ceuta', 'Africa/Conakry', 'Africa/Dakar', 'Africa/Dar_es_Salaam', 'Africa/Djibouti', 'Africa/Douala', 'Africa/El_Aaiun', 'Africa/Freetown', 'Africa/Gaborone', 'Africa/Harare', 'Africa/Johannesburg', 'Africa/Juba', 'Africa/Kampala', 'Africa/Khartoum', 'Africa/Kigali', 'Africa/Kinshasa', 'Africa/Lagos', 'Africa/Libreville', 'Africa/Lome', 'Africa/Luanda', 'Africa/Lubumbashi', 'Africa/Lusaka', 'Africa/Malabo', 'Africa/Maputo', 'Africa/Maseru', 'Africa/Mbabane', 'Africa/Mogadishu', 'Africa/Monrovia', 'Africa/Nairobi', 'Africa/Ndjamena', 'Africa/Niamey', 'Africa/Nouakchott', 'Africa/Ouagadougou', 'Africa/Porto-Novo', 'Africa/Sao_Tome', 'Africa/Tripoli', 'Africa/Tunis', 'Africa/Windhoek', 'America/Adak', 'America/Anchorage', 'Amer

In [33]:
now_day=pd.Period.now(freq="D") # "H"
now_day

Period('2019-08-13', 'D')

In [38]:
now.to_period("H")

Period('2019-08-13 16:00', 'H')

# numpy

Python虽然也提供了array模块，但其只支持一维数组，不支持多维数组(在TensorFlow里面偏向于矩阵理解)，也没有各种运算函数。因而不适合数值运算。

In [43]:
import numpy as np 

In [48]:
np.random.randn(6, 4)

array([[-0.37704517, -0.32125706, -0.22033442,  1.01846384],
       [-0.51572719,  1.15390238, -0.47695464, -0.18275903],
       [-1.08117539,  0.55839355, -0.37408577, -0.58406115],
       [ 0.13863662,  1.39243894,  0.55775951,  0.28754048],
       [ 0.15897817, -1.60361054, -1.82961434, -1.60044141],
       [-0.43663115, -1.34093554,  0.2800148 ,  2.73953033]])

In [45]:
np.array([2,3,4])

array([2, 3, 4])

In [47]:
np.array([[1,2],[3,4]],dtype=complex)

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [50]:
np.array([3] * 4, dtype='int32')

array([3, 3, 3, 3])

In [51]:
pd.Categorical(["test", "train", "test", "train"]),

([test, train, test, train]
 Categories (2, object): [test, train],)

# Series

Pandas模块的数据结构主要有两：1、Series ；2、DataFrame

series是一个一维数组，是基于NumPy的ndarray结构。Pandas会默然用0到n-1来作为series的index，但也可以自己指定index(可以把index理解为dict里面的key)

In [52]:
pd.Series(2, index=list(range(6)), dtype='float32')

0    2.0
1    2.0
2    2.0
3    2.0
4    2.0
5    2.0
dtype: float32

# pandas

## 基本操作

In [62]:
df = pd.DataFrame({'A': 1.,
                    'B': pd.Timestamp('20130102'),
                    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D': np.array([3] * 4, dtype='int32'),
                    'E': pd.Categorical(["test", "train", "test", "train"]),
                    'F': 'foo'})

In [57]:
df.dtypes 

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [ ]:
df.head()
df.tail()
df.index()
df.columns

In [59]:
df.describe()

A    C    D
count  4.0  4.0  4.0
mean   1.0  1.0  3.0
std    0.0  0.0  0.0
min    1.0  1.0  3.0
25%    1.0  1.0  3.0
50%    1.0  1.0  3.0
75%    1.0  1.0  3.0
max    1.0  1.0  3.0

In [ ]:
df.T

In [ ]:
df['A']

In [ ]:
df[0:3]
df['20130102':'20130104']
df.loc[dates[0]]
df.loc[:, ['A', 'B']]
df.loc['20130102':'20130104', ['A', 'B']]
df.loc['20130102', ['A', 'B']]
df.loc[dates[0], 'A']
df.at[dates[0], 'A']

In [ ]:
df.iloc[3]
df.iloc[3:5, 0:2]
df.iloc[[1, 2, 4], [0, 2]]
df.iloc[1:3, :]
df.iloc[:, 1:3]
df.iloc[1, 1]
df.iat[1, 1]

In [ ]:
df[df.A > 0]
df[df > 0]

In [66]:
df2 = df.copy()
df2['E'] = ['two', 'three', 'four', 'three']
df2[df2['E'].isin(['two', 'four'])]

A          B    C  D    E    F
0  1.0 2013-01-02  1.0  3  two  foo

In [74]:
s1 = pd.Series([1, 2, 3, 4], index=pd.date_range('20130102', periods=4))

In [75]:
df['F'] = s1
dates = pd.date_range('20130102', periods=4)
df.at[dates[0], 'A'] = 0
df

A          B    C    D      E    F
0                    1.0 2013-01-02  1.0  3.0   test  NaN
1                    1.0 2013-01-02  1.0  3.0  train  NaN
2                    1.0 2013-01-02  1.0  3.0   test  NaN
3                    1.0 2013-01-02  1.0  3.0  train  NaN
2013-01-02 00:00:00  0.0        NaT  NaN  NaN    NaN  1.0

In [72]:

df.loc[:, 'D'] = np.array([5] * len(df))

## df. sort_index()

**作用：**默认根据行标签对所有行排序，或根据列标签对所有列排序，或根据指定某列或某几列对行排序。  
**注意：**df. sort_index()可以完成和df. sort_values()完全相同的功能，但python更推荐用只用df. sort_index()对“根据行标签”和“根据列标签”排序，其他排序方式用df.sort_values()。

sort_index(axis=0, level=None, ascending=True, inplace=False, kind='quicksort', na_position='last',sort_remaining=True, by=None)  
**axis：**0按照行名排序；1按照列名排序  
**level：**默认None，否则按照给定的level顺序排列---貌似并不是，文档  
**ascending：**默认True升序排列；False降序排列  
**inplace：**默认False，否则排序之后的数据直接替换原来的数据框  
**kind：**排序方法，{‘quicksort’, ‘mergesort’, ‘heapsort’}, default ‘quicksort’。似乎不用太关心。  
**na_position：**缺失值默认排在最后{"first","last"}  
**by：**按照某一列或几列数据进行排序，但是by参数貌似不建议使用

## df. sort_values()

**作用：**既可以根据列数据，也可根据行数据排序。  
**注意：**必须指定by参数，即必须指定哪几行或哪几列；无法根据index名和columns名排序（由.sort_index()执行）

DataFrame.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')  
**axis：**{0 or ‘index’, 1 or ‘columns’}, default 0，默认按照列排序，即纵向排序；如果为1，则是横向排序。  
**by：**str or list of str；如果axis=0，那么by="列名"；如果axis=1，那么by="行名"。  
**ascending：**布尔型，True则升序，如果by=['列名1','列名2']，则该参数可以是[True, False]，即第一字段升序，第二个降序。  
**inplace：**布尔型，是否用排序后的数据框替换现有的数据框。  
**kind：**排序方法，{‘quicksort’, ‘mergesort’, ‘heapsort’}, default ‘quicksort’。似乎不用太关心。  
**na_position：**{‘first’, ‘last’}, default ‘last’，默认缺失值排在最后面。

## df[]

【干货】https://jingyan.baidu.com/article/0eb457e508b6d303f0a90572.html

In [ ]:
df[df.freq>0]
df[['A','B']][(df.D>0)&(df.C>0)]

## 查找NA

In [1]:
import pandas as pd
data = [[None, None, 90, 80],[57, 43, 89, 65],[78, 50, 67, 78],[None, 78, 90, 73],[67, 45, 78, 76],[77, 88, None, 45],[52, 110, 120, 99],[131, 13, 32, 12]]
index = ['语文', '英语', '数学', '政治', '物理', '化学', '生物', '地理']
column = ['张三', '李四', '王五', '周六']
data = pd.DataFrame(data,index=index,columns=column)
print(data)
print("=========================================================\n")
for columname in data.columns:
    if data[columname].count() != len(data):
         loc = data[columname][data[columname].isnull().values==True].index.tolist()
         print('列名："{}", 第{}行位置有缺失值'.format(columname,loc))

       张三     李四     王五  周六
语文    NaN    NaN   90.0  80
英语   57.0   43.0   89.0  65
数学   78.0   50.0   67.0  78
政治    NaN   78.0   90.0  73
物理   67.0   45.0   78.0  76
化学   77.0   88.0    NaN  45
生物   52.0  110.0  120.0  99
地理  131.0   13.0   32.0  12

列名："张三", 第['语文', '政治']行位置有缺失值
列名："李四", 第['语文']行位置有缺失值
列名："王五", 第['化学']行位置有缺失值


## 将series转为dataframe（value_counts使用）

In [ ]:
1、to_frame()方法

In [ ]:
import pandas as pd


dict_month = {'month':month.index,'numbers':month.values}

df_month = pd.DataFrame(dict_month)